name: glowdating
description: Glow Video Chat


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 4.0.02+133

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animator: ^3.3.0
  flutter_flushbar: ^0.0.2
  avatar_glow: ^2.0.2
  circular_bottom_navigation: ^2.3.0
  loading_indicator: ^3.1.1
  shimmer: ^3.0.0
  spring_button: ^2.0.0
  http: ^1.1.0
  image_picker: ^1.0.4
  rflutter_alert: ^2.0.7
  flutter_cupertino_datetime_picker: ^3.0.0
  date_format: ^2.0.7
  shared_preferences: ^2.2.2
  agora_rtc_engine: ^6.2.6
  permission_handler: ^11.2.0
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  platform_device_id: ^1.0.1
  image: ^4.1.3
  image_cropper: ^5.0.0
  progress_dialog_null_safe: ^1.0.7
  socket_io_client: 1.0.2
  logger: ^2.0.2+1
  circular_profile_avatar: ^2.0.5
  wave: ^0.2.2
  cached_network_image: ^3.3.0
  firebase_core: 2.25.5
  firebase_messaging: 14.7.17
  bot_toast: ^4.1.1
  share: ^2.0.4
  flutter_staggered_animations: ^1.1.1
  webview_flutter: ^4.4.1
  audioplayers: ^5.2.0
  toggle_switch: ^2.1.0
  font_awesome_flutter: ^10.6.0
  matrix4_transform: ^2.0.1
  in_app_purchase: ^3.1.11
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_translate: ^4.0.3
  firebase_analytics: 10.8.6
  devicelocale: ^0.7.0
  url_launcher: ^6.1.11
  introduction_screen: ^3.0.0
  flutter_spinkit: ^5.2.0
  flare_flutter: ^3.0.2
  photo_view: ^0.14.0
  flutter_screenutil: ^5.7.0
  animated_text_kit: ^4.2.2
  flick_video_player: ^0.7.0
  fluttertoast: ^8.2.2
  path_provider: ^2.1.1
  flutter_screenshot_switcher: ^2.5.0
  advertising_id: ^2.5.0
  adjust_sdk: ^4.35.2
  flutter_device_type: ^0.4.0
  purchases_flutter: ^6.0.0
  bordered_text: ^2.0.0
  flutter_styled_toast: ^2.1.3
  safe_device: ^1.1.4
  animated_widgets: ^1.1.0
  launch_review: ^3.0.1
  flutter_secure_storage: 8.1.0
  fading_edge_scrollview: ^3.0.0
  flutter_animator: ^3.2.2
  random_color: ^1.0.6-nullsafety
  color: ^3.0.0
  facebook_app_events: ^0.19.2
  admost_flutter_plugin: ^1.3.1
  appsflyer_sdk: ^6.14.2
  firebase_crashlytics: 3.4.15
  dots_indicator: ^3.0.0
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  email_validator: ^2.1.17
  mask_text_input_formatter: ^2.5.0
  google_sign_in: ^6.1.5
  in_app_review: ^2.0.8
  app_tracking_transparency: ^2.0.4
  image_crop: ^0.4.1
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  flutter_rating_bar: ^4.0.1
  lottie: ^2.3.2
  uni_links: ^0.5.1
  dotted_border: ^2.1.0
  country_code_picker: ^3.0.0
  google_fonts: ^6.1.0
  app_settings: ^5.1.1
  extended_image: ^8.1.1
  android_play_install_referrer: ^0.3.0
  dropdown_button2: ^2.1.4
  flutter_iconly: ^1.0.2
  multi_select_flutter: ^4.1.3
  flutter_native_splash: ^2.2.19
  device_preview: ^1.1.0
  camera: ^0.10.5+7
  shorts_video_record_button: ^0.0.2
  gallery_picker: ^0.4.8
  media_picker_widget: ^1.0.6
  video_editor: ^3.0.0
  ffmpeg_kit_flutter: ^6.0.3
  fraction: ^5.0.2
  dash_chat_2: ^0.0.19
  translator: ^0.1.7
  audio_waveforms: ^1.0.4
  voice_message_package: 2.1.3
  video_player: ^2.8.2
  pod_player: ^0.2.1
  appinio_video_player: ^1.2.2
  border_progress_indicator: ^0.0.3
  better_player: ^0.0.83
  flutter_video_view: ^2.0.2+1
  chunked_uploader: ^1.1.0
  dio: ^5.4.0
  custom_image_crop: ^0.0.13
  blur: ^3.1.0
  animate_gradient: ^0.0.2+1
  google_mobile_ads: ^5.0.0
  ironsource_mediation: ^1.2.1



dependency_overrides:
  win32: ^5.0.0
  geolocator_android: 4.1.4
  photo_manager: 3.0.0-dev.5
  permission_handler: ^11.2.0
  audioplayers: ^5.2.0
  logger: ^2.0.2+1
  navigation_builder: ^0.0.4
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3



flutter_icons:
  image_path: "assets/icon.png"
  #image_path_android: "assets/images/icon-710x599-android.png"
  #image_path_ios: "assets/images/icon-710x599-ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  #adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/lottie/
    - assets/images/premium/
    - assets/images/gif/
    - assets/images/gift/
    - assets/images/onboard/
    - assets/sounds/
    - assets/ca/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/Fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/Fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
